# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

linter:
  # The lint rules applied to this project can be customized in the
  # section below to disable rules from the `package:flutter_lints/flutter.yaml`
  # included above or to enable additional rules. A list of all available lints
  # and their documentation is published at
  # https://dart-lang.github.io/linter/lints/index.html.
  #
  # Instead of disabling a lint rule for the entire project in the
  # section below, it can also be suppressed for a single line of code
  # or a specific dart file by using the `// ignore: name_of_lint` and
  # `// ignore_for_file: name_of_lint` syntax on the line or in the file
  # producing the lint.
  rules:
    # avoid_print: false  # Uncomment to disable the `avoid_print` rule
    # prefer_single_quotes: true  # Uncomment to enable the `prefer_single_quotes` rule

analyzer:
  exclude:
    - lib/base_course/01/**
    - lib/base_course/02/**
    - lib/base_course/03/**
    - lib/base_course/04/**
    - lib/base_course/05/**
    - lib/base_course/06/**
    - lib/base_course/07/**
    - lib/base_course/08/**
    - lib/base_course/09/**
    - lib/base_course/10/**
    - lib/base_course/11/**
    - lib/base_course/12/**
    - lib/base_course/13/**
    - lib/base_course/14/**
    - lib/base_course/15/**
    - lib/base_course/16/**
    - lib/base_course/17/**
    - lib/base_course/18/**
    - lib/base_course/19/**
    - lib/base_course/20/**
    - lib/base_course/21/**
    - lib/base_course/22/**


    - lib/space_shooting/**

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
